const INSTALLATION_ERROR = "INSTALLATION_ERROR";
const CREATE_FOLDER_ERROR = "CREATE_FOLDER_ERROR";
const UNKNOWN_ERROR = "UNKNOWN_ERROR";

module.exports = {
  INSTALLATION_ERROR,
  CREATE_FOLDER_ERROR,
  UNKNOWN_ERROR,
};
