const meta = {
  comps: [],
  compsSource: "",
  appMain: "",
  lastCompsCount: 12,
  compsPaths: [],
  app: {
    type: "ssr",
    stateVendor: "redux",
  },
  alias: {
    Layouts: "/src/components/layout/index",
    Pages: "/src/components/pages/index",
    Docs: "/src/components/docs/index",
    Markdowns: "/src/mds/",
    Modules: "/src/modules/",
    Startup: "/src/components/startup/index",
    UI: "/src/components/ui/index",
    Config: "/src/config/",
    HOC: "/src/hoc/",
    Hooks: "/src/hooks/index",
    Context: "/src/context/",
    Language: "/src/language/index",
    AppRoutes: "/src/routes/",
    AppModules: "/src/modules/",
    Store: "/src/store/",
    Utilities: "/src/utils/index",
    Services: "/src/services/",
    Constants: "/src/constants/",
    Assets: "/src/assets/index",
    AppGlobals: "/src/globals/index",
  },
};
export { meta };
