const meta = {
  comps: [],
  compsSource:
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src",
  appMain:
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr",
  lastCompsCount: 12,
  compsPaths: [
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/test.js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/privacy.js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/index.js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/faqs.js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/contact-us.js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/about.js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/todo/index.js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/posts/index.js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/posts/[slug].js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/connection.js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/testing.js",
    "/Users/surprisemashele/Documents/kotii/packages/kotii-templates/javascript/ssr/src/pages/test_jsx.js",
  ],
  app: {
    type: "ssr",
    stateVendor: "redux",
  },
  alias: {
    Layouts: "/src/components/layout/index",
    Pages: "/src/components/pages/index",
    Docs: "/src/components/docs/index",
    Markdowns: "/src/mds/",
    Modules: "/src/modules/",
    Startup: "/src/components/startup/index",
    UI: "/src/components/ui/index",
    Config: "/src/config/",
    HOC: "/src/hoc/",
    Hooks: "/src/hooks/index",
    Context: "/src/context/",
    Language: "/src/language/index",
    AppRoutes: "/src/routes/",
    AppModules: "/src/modules/",
    Store: "/src/store/",
    Utilities: "/src/utils/index",
    Services: "/src/services/",
    Constants: "/src/constants/",
    Assets: "/src/assets/index",
    AppGlobals: "/src/globals/index",
  },
};
export { meta };
